steps:
- task: Npm@1
  displayName: 'Install TypeScript & Jest'
  inputs:
    command: install
- task: Npm@1
  displayName: 'Run tests'
  inputs:
    command: custom
    verbose: true
    customCommand: test
- task: PublishTestResults@2
  displayName: 'Publish tests'
  inputs:
    testResultsFiles: junit.xml
# TODO: Do is at the end when TypeScript is fixed and in a Release pipeline when they support YAML
- task: Npm@1
  inputs:
    command: publish
    publishEndpoint: 'NPM connection'
- powershell: npx tsc -p .
  displayName: 'Run type check'
